# Generated by Django 4.2.1 on 2023-05-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
